### ISSUE TITLE
CAN analyzer software

### ISSUE THREAD

**Issue by romixlab** [suburbanembedded/hadoucan-fw#31]
What software would you recommend to use with your hardware? It seems that CANHacker might be an option, not sure about compatibility though.

**Comment by jacobschloss** [comment]
Most linux software that uses the socketcan APIs should work with the slcand bridge if you don't need CANFD support. I have a patch to add CANFD support to the linux slcan driver but have not tested it enough to release. Wireshark can work as a socketcan packet viewer, and candump works too.

I can't tell if CAN-Hacker / CARBUS use the slcan protocol. If they do, you might be able to use their GUI.

I don't have any recommendations for car specific software, but would be interested in getting support. Right now intended use is with custom applications with either our C++ API, or a 3rd party slcan api.

- https://python-can.readthedocs.io/en/master/interfaces/slcan.html
- https://github.com/suburbanembedded/hadoucan_util

**Comment by jacobschloss** [comment]
It looks like CANHacker might support slcan, worth a try.
